server:
  port: 9001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/nami?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html

nami:
  server-web-socket-url: ws://127.0.0.1:9999
  user-password-salt: d5ec0a02

nacos:
  discovery:
    server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

