spring:
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    producer:
      retries: 0
      acks: all
    consumer:
      properties:
        group:
          id: defaultConsumerGroup
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: latest
    listener:
      missing-topics-fatal: false
